spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: root
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
